import fs from "node:fs/promises";

const SHOPIFY_STORE_DOMAIN = process.env.SHOPIFY_STORE_DOMAIN;
const SHOPIFY_CLIENT_ID = process.env.SHOPIFY_CLIENT_ID;
const SHOPIFY_CLIENT_SECRET = process.env.SHOPIFY_CLIENT_SECRET;

const API_VERSION = "2026-07";

if (!SHOPIFY_STORE_DOMAIN || !SHOPIFY_CLIENT_ID || !SHOPIFY_CLIENT_SECRET) {
  throw new Error("Missing Shopify environment variables.");
}

/*
  SECURITY:
  - This file is DRY-RUN ONLY.
  - It NEVER writes prices to Shopify.
  - It only reads products/variants/metafields.
*/

async function getAccessToken() {
  const response = await fetch(
    `https://${SHOPIFY_STORE_DOMAIN}/admin/oauth/access_token`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        client_id: SHOPIFY_CLIENT_ID,
        client_secret: SHOPIFY_CLIENT_SECRET,
        grant_type: "client_credentials"
      })
    }
  );

  if (!response.ok) {
    throw new Error(
      `Shopify authentication failed: ${response.status} ${await response.text()}`
    );
  }

  const data = await response.json();

  if (!data.access_token) {
    throw new Error("Shopify access token was not returned.");
  }

  return data.access_token;
}

async function shopifyGraphQL(token, query, variables = {}) {
  const response = await fetch(
    `https://${SHOPIFY_STORE_DOMAIN}/admin/api/${API_VERSION}/graphql.json`,
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-Shopify-Access-Token": token
      },
      body: JSON.stringify({
        query,
        variables
      })
    }
  );

  const data = await response.json();

  if (!response.ok) {
    throw new Error(
      `Shopify API HTTP error ${response.status}: ${JSON.stringify(data)}`
    );
  }

  if (data.errors?.length) {
    throw new Error(
      `Shopify GraphQL error: ${JSON.stringify(data.errors)}`
    );
  }

  return data.data;
}

async function getGoldPrices() {
  /*
    We currently use the scraper output generated by scraper.js.

    Expected output:
    {
      "24K": number,
      "18K": number,
      "14K": number,
      "10K": number
    }
  */

  try {
    const file = await fs.readFile(
      "gold-prices.json",
      "utf8"
    );

    const prices = JSON.parse(file);

    validateGoldPrices(prices);

    return prices;
  } catch {
    throw new Error(
      "gold-prices.json not found. We will connect scraper.js to this file in the next step."
    );
  }
}

function validateGoldPrices(prices) {
  const required = ["24K", "18K", "14K", "10K"];

  for (const key of required) {
    if (
      typeof prices[key] !== "number" ||
      !Number.isFinite(prices[key]) ||
      prices[key] <= 0
    ) {
      throw new Error(`Invalid ${key} gold price.`);
    }
  }

  // Verify purity calculations have not been corrupted.
  const expected18 = prices["24K"] * 18 / 24;
  const expected14 = prices["24K"] * 14 / 24;
  const expected10 = prices["24K"] * 10 / 24;

  const tolerance = 0.01;

  if (Math.abs(prices["18K"] - expected18) > tolerance) {
    throw new Error("18K price failed purity validation.");
  }

  if (Math.abs(prices["14K"] - expected14) > tolerance) {
    throw new Error("14K price failed purity validation.");
  }

  if (Math.abs(prices["10K"] - expected10) > tolerance) {
    throw new Error("10K price failed purity validation.");
  }
}

const SHOPIFY_QUERY = `
  query GetVariants($first: Int!, $after: String) {
    productVariants(first: $first, after: $after) {
      nodes {
        id
        title
        sku
        price
        product {
          id
          title
        }
        metafields(first: 50) {
          nodes {
            namespace
            key
            value
            type
          }
        }
      }

      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
`;

async function getAllVariants(token) {
  const variants = [];
  let after = null;

  do {
    const data = await shopifyGraphQL(
      token,
      SHOPIFY_QUERY,
      {
        first: 250,
        after
      }
    );

    const connection = data.productVariants;

    variants.push(...connection.nodes);

    after = connection.pageInfo.hasNextPage
      ? connection.pageInfo.endCursor
      : null;

  } while (after);

  return variants;
}

function getMetafield(variant, key) {
  const metafield = variant.metafields.nodes.find(
  (item) =>
    item.namespace === "custom" &&
    item.key.toLowerCase() === key.toLowerCase()
);

  return metafield?.value ?? null;
}

function numberFromMetafield(value, name) {
  if (value === null || value === undefined || value === "") {
    throw new Error(
      `${name} metafield is missing.`
    );
  }

  const number = Number(value);

  if (!Number.isFinite(number) || number < 0) {
    throw new Error(
      `${name} metafield contains an invalid number: ${value}`
    );
  }

  return number;
}

function calculatePrice({
  metal,
  goldWeight,
  diamondCost,
  otherCost,
  goldPrices
}) {
  let metalRate;

  const normalizedMetal = metal.trim().toUpperCase();

  if (normalizedMetal === "SILVER") {
    metalRate = 300;
  } else if (
    normalizedMetal === "10K" ||
    normalizedMetal === "14K" ||
    normalizedMetal === "18K"
  ) {
    metalRate = goldPrices[normalizedMetal];
  } else {
    throw new Error(
      `Unsupported metal: ${metal}`
    );
  }

  const metalCost = goldWeight * metalRate;

  const makingCost = metalCost * 0.12;

  const baseCost =
    metalCost +
    diamondCost +
    makingCost +
    otherCost;

  const sellingPriceINR = baseCost * 1.9;

  const sellingPriceUSD = sellingPriceINR / 97;

  return {
    metalRate,
    metalCost,
    makingCost,
    baseCost,
    sellingPriceINR,
    sellingPriceUSD
  };
}

function validateCalculatedPrice(result) {
  if (
    !Number.isFinite(result.sellingPriceINR) ||
    !Number.isFinite(result.sellingPriceUSD) ||
    result.sellingPriceINR <= 0 ||
    result.sellingPriceUSD <= 0
  ) {
    throw new Error("Calculated price failed safety validation.");
  }

  // Absolute upper safety limit.
  // This is a temporary protection until we add
  // per-product historical price checks.
  if (result.sellingPriceUSD > 1000000) {
    throw new Error(
      "Calculated price exceeds emergency safety limit."
    );
  }
}

async function main() {
  console.log("======================================");
  console.log("JEWELRY PRICE AUTOMATION - DRY RUN");
  console.log("======================================");

  console.log("\nAuthenticating with Shopify...");

  const token = await getAccessToken();

  console.log("Shopify authentication successful.");

  console.log("\nReading validated gold prices...");

  const goldPrices = await getGoldPrices();

  console.log(goldPrices);

  console.log("\nSilver rate: ₹300/g");

  console.log("\nReading Shopify variants...");

  const variants = await getAllVariants(token);

  console.log(`Found ${variants.length} variant(s).`);

  let processed = 0;
  let skipped = 0;

  for (const variant of variants) {
    try {
      const metal = getMetafield(
        variant,
        "metal"
      );

      const goldWeight = numberFromMetafield(
        getMetafield(variant, "gold_weight"),
        "Gold Weight"
      );

      const diamondCost = numberFromMetafield(
        getMetafield(variant, "diamond_cost"),
        "Diamond Cost"
      );

      const otherCost = numberFromMetafield(
        getMetafield(variant, "other_cost"),
        "Other Cost"
      );

      if (!metal) {
        throw new Error("Metal metafield is missing.");
      }

      const result = calculatePrice({
        metal,
        goldWeight,
        diamondCost,
        otherCost,
        goldPrices
      });

      validateCalculatedPrice(result);

      console.log("\n--------------------------------------");
      console.log(`Product: ${variant.product.title}`);
      console.log(`Variant: ${variant.title}`);
      console.log(`SKU: ${variant.sku ?? "N/A"}`);
      console.log(`Metal: ${metal}`);
      console.log(`Gold Weight: ${goldWeight} g`);
      console.log(`Diamond Cost: ₹${diamondCost}`);
      console.log(`Other Cost: ₹${otherCost}`);
      console.log(`Metal Rate: ₹${result.metalRate}/g`);
      console.log(`Metal Cost: ₹${result.metalCost.toFixed(2)}`);
      console.log(`Making Cost (12%): ₹${result.makingCost.toFixed(2)}`);
      console.log(`Base Cost: ₹${result.baseCost.toFixed(2)}`);
      console.log(
        `PROPOSED INR PRICE: ₹${result.sellingPriceINR.toFixed(2)}`
      );
      console.log(
        `PROPOSED USD PRICE: $${result.sellingPriceUSD.toFixed(2)}`
      );
      console.log(`CURRENT SHOPIFY PRICE: ${variant.price}`);
      console.log("ACTION: DRY RUN — NO UPDATE");

      processed++;

    } catch (error) {
      skipped++;

      console.log("\n--------------------------------------");
      console.log(`SKIPPED: ${variant.product.title}`);
      console.log(`Variant: ${variant.title}`);
      console.log(`Reason: ${error.message}`);
      console.log("ACTION: NO UPDATE");
    }
  }

  console.log("\n======================================");
  console.log("DRY RUN COMPLETE");
  console.log("======================================");
  console.log(`Processed: ${processed}`);
  console.log(`Skipped: ${skipped}`);
  console.log("Shopify prices were NOT changed.");
}

await main();
